hong_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
kong_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

# kdl_kinematics_plugin/KDLKinematicsPlugin
# ur_kinematics/UR10KinematicsPlugin
# trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
