# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - kong_shoulder_pan_joint
     - kong_shoulder_lift_joint
     - kong_elbow_joint
     - kong_wrist_1_joint
     - kong_wrist_2_joint
     - kong_wrist_3_joint

# Publish all joint states ----------------------------------
kong_joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
kong_force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
kong_pos_based_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - kong_shoulder_pan_joint
     - kong_shoulder_lift_joint
     - kong_elbow_joint
     - kong_wrist_1_joint
     - kong_wrist_2_joint
     - kong_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      kong_shoulder_pan_joint: {trajectory: 0.5, goal: 0.5}
      kong_shoulder_lift_joint: {trajectory: 0.5, goal: 0.5}
      kong_elbow_joint: {trajectory: 0.5, goal: 0.5}
      kong_wrist_1_joint: {trajectory: 0.5, goal: 0.5}
      kong_wrist_2_joint: {trajectory: 0.5, goal: 0.5}
      kong_wrist_3_joint: {trajectory: 0.5, goal: 0.5}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5
